<?php
	require_once("functions/layout.inc.php");
	
	pre();
		$year = date("Y");
		//$year = "2009";
		print "<div style=\"width:700px\">";
			print "<h2>Stand 3e klasse D in kalenderjaar ".$year."</h2>";
			$stand = new Stand(date("Y-m-d"));
			$rows = $stand->getYearTable($year);
			print "<table cellspacing=\"0\" style=\"border: 2px solid #00937A;\">";
			$i=1;
			print "<tr>";
				print "<td align=\"right\" class=\"stand_header\">";
					print "Ps";
				print "</th>";
				print "<td style=\"width:120px\" class=\"stand_header\" align=\"center\">";
					print "Team";
				print "</td>";
				print "<td class=\"stand_header\">";
					print "GS";
				print "</td>";
				print "<td class=\"stand_header\">";
					print "GW";
				print "</td>";
				print "<td class=\"stand_header\">";
					print "GL";
				print "</td>";
				print "<td class=\"stand_header\">";
					print "VL";
				print "</td>";
				print "<td class=\"stand_header\">";
					print "PT";
				print "</th>";
				print "<td class=\"stand_header\">";
					print "DV";
				print "</td>";
				print "<td class=\"stand_header\">";
					print "DT";
				print "</td>";
				print "<td class=\"stand_header\">";
					print "DS";
				print "</td>";
				print "<td class=\"stand_header\">";
					print "PCT";
				print "</td>";
			print "</tr>";
			foreach($rows as $row){
				print "<tr>";
					print "<td class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
						print $i.".";
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
					print "<td style=\"width:120px;text-align:left\" class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
						print $row['teamnaam'];
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
					print "<td class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
						print $row['gespeeld'];
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
					print "<td class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
						print $row['gewonnen'];
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
					print "<td class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
						print $row['gelijk'];
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
					print "<td class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
						print $row['verloren'];
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
					print "<td class=\"stand\">";
						print "<b>".$row['punten']."</b>";
					print "</td>";
					print "<td class=\"stand\">";
						print "(";
						print ($row['teamid']==2) ? "<b>" : "";
						print $row['voor'];
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
					print "<td  class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
						print $row['tegen'];
						print ($row['teamid']==2) ? "</b>" : "";
						print ")";
					print "</td>";
					print "<td  class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
						if(substr($row['saldo'],0,1)!=="-")
							print "+";
						print $row['saldo'];
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
					print "<td  class=\"stand\">";
						print ($row['teamid']==2) ? "<b>" : "";
                        if($row{'gespeeld'}<>0)
						    print round((($row['gewonnen']*3 + $row['gelijk'])/($row['gespeeld'] * 3)) * 100 , 1);
						else
                            print "0";
                        print "%";
						print ($row['teamid']==2) ? "</b>" : "";
					print "</td>";
				print "</tr>";
				$i++;
			}
			print "</table>";
		print "</div>";
		
	post();
?>
